### PR TITLE
Additional features

### PR DESCRIPTION
**Pull request by matias-pizarro**
Hey Stanislas,

Love focker!

In case you are interested in merging this upstream, I added a tree command that paints a genealogical tree of images and made network interface specification controllable by an environment variable.

Best,

Matías

### CODE REVIEW

**Comment by sadaszewski** [comment]
Hi Matias, many thanks for your work (sounds great) and for your kind
words. I will definitely take a look and see if it should be structured as
a part of focker core or as an extension. I would like to keep the focker
essentials as lean as possible. Best regards, -- Stanislaw

**Comment by matias-pizarro** [comment]
Hey Stan, it would be great if you let me know how you want extensions structured, or point me to an example - Best, Matías

**Comment by sadaszewski** [comment]
Hi Matias,

In a commit just now: https://github.com/sadaszewski/focker/commit/7962218bd7e2efe5aac0d3bd2b766d97a43b82d3 I have added support for plugins.

The convention is the following. Any package with a name starting with focker_ will be loaded as a plugin.

You can find an example here: https://github.com/sadaszewski/focker/tree/master/plugin-example/focker-dummy-plugin

The hooks supported are the following:

on_focker_start()
on_focker_create_parser(parser, parser_dict)
on_focker_parse_args(args)
on_focker_pre_command_(L1_command)_(L2_command)(args)
on_focker_post_command_(L1_command)_(L2_command)(args)
on_focker_quit(args)

where L1_command is e.g. "image" and L2_command is e.g. "build".

Hopefully those hooks can provide enough opportunities to modify the parser, the arguments and the pre- and post-behavior of any command so that one can implement useful new functionality without modifying the focker core.

You should still be able to import from the focker package in your plugins code so you should have access to all the focker core functionality.

Please let me know if that helps.

Kind regards,

--
Stanislaw

**Comment by sadaszewski** [comment]
PS. One more thing that would be nice to intercept are all calls to subprocess.run() and similar, I will try to cook something up tomorrow.

**Comment by sadaszewski** [comment]
Ok added support for e.g. modify_jail_run_command(command, stack_names,
frame) where the return value should contain the modified command line.
stack_names contains strings e.g. [command_image_build, build, execute,
jail_run] indicating where the call originates from. frame contains the
frame from inspect.currentframe() call just before running the command.
This coupled with the previously mentioned functionality should allow to
implement your changes fully as a plugin. It would be great if you could do
that and then we can see how to make the plugins mechanism a bit nicer
perhaps.

Best regards,

--
Stanislaw

**Comment by sadaszewski** [comment]
With the release of Focker 2.0 the new plugin architecture should be more enough to accomodate this use case.

**Pull request closed without merging**
